package com.capstone.recipefinder.utils

const val BASE_URL = "https://backend-dot-recipe-finder-388213.as.r.appspot.com/"
const val RETROFIT_TAG = "Retrofit"
const val SHARED_PREFERENCES = "shared_preferences"
const val PREFS_NAME = "login"
const val NAME = "name"
const val TOKEN = "token"
const val USER_ID = "userId"
const val LOGIN_STATE = "login_state"
const val EXTRA_IMAGE = "img"
const val EXTRA_DESCRIPTION = "extra_description"
const val DESCRIPTION = "description"
const val INGREDIENT = "ingredient"
const val EXTRA_INGREDIENT = "extra_ingredient"
const val FOOD_NAME = "name"
const val NUTRITION = "nutrion"
const val KALORI = "Kalori"
const val PROTEIN = "protein"
const val LEMAK = "lemak"
const val KARBOHIDRAT = "karbohidrat"
const val CATEGORY = "category"
const val ID_CATEGORY = "id_category"
const val INDEX = "idx"
